### ISSUE TITLE
V10 support?

### ISSUE THREAD

**Issue by geoidesic** [oOve/FollowMe#4]
Hi,

Just a reminder that this (very useful) mod isn't currently working with the stable release of Foundry.

**Comment by nirurin** [comment]
Is it not? The update release says v10 support. I can't test it as I'm not yet on v10, but I came to check to see if this had been updated...

**Comment by geoidesic** [comment]
Nope. It pretends to work and gives a message "Installed successfully" but it doesn't appear in the list of installed modules.

**Comment by geoidesic** [comment]
Actually this is working in v10. Never mind.
